Repository kowhai-2018/Final-Project, pull requests merged in 2018-12, with the labels that each got.

#18 added chart pieces to FE
  db/index.js
  package.json
  yarn.lock
Labels: client

#33 29 create add rating function
  server/routes/users.js
  server/server.js
Labels: database, server

#34 delete index.js, empty file
  db/index.js
Labels: invalid, server

#53 37 pwa add manifest
  server/public/images/touch/icon128.png
  server/public/images/touch/icon144.png
  server/public/images/touch/icon168.png
  server/public/images/touch/icon192.png
  server/public/images/touch/icon48.png
  server/public/images/touch/icon72.png
  server/public/images/touch/icon96.png
  server/public/index.html
  server/public/manifest.webmanifest
  server/public/style/main.css
Labels: client, design, enhancement

#70 testing heroku library for https
  package.json
  server/server.js
  yarn.lock
Labels: Deployment, server

#84 80 add reducers
  client/actions/journalActions.js
  client/components/CardList.jsx
  client/components/Rating/Smiley.jsx
  client/index.js
  client/reducer/activities.js
  client/reducer/index.js
  package.json
  server/server.js
  yarn.lock
Labels: client

#85 added key to smilies rating. Error no longer comes up
  client/components/ActivityCard.jsx
  client/components/CardList.jsx
  seeds/activities.js
Labels: bug

#89 Merging responsiveness into PWA
  client/actions/journalActions.js
  client/components/ActivityCard.jsx
  client/components/CardList.jsx
  client/index.js
  client/reducer/activities.js
  client/reducer/index.js
  seeds/activities.js
  server/public/index.html
  server/public/main.css
  server/public/style/main.css
Labels: Deployment

#102 68 graph action
  client/actions/graph.js
  client/components/Graph.jsx
  client/components/Main.jsx
  client/components/Statistics.jsx
  client/reducer/graph.js
  client/reducer/index.js
  seeds/cardData.js
  seeds/dates.js
  server/db/graph.js
  server/routes/dates.js
Labels: client, server

#101 93-activityLog modal component
  client/components/ActivityCard.jsx
  client/components/ActivityLog.jsx
  client/components/App.jsx
  server/public/main.css
Labels: client

#117 Changed start url to "/"
  server/public/manifest.webmanifest
Labels: bug

#120 999 pwa db rebuilt
  knexfile.js
  package.json
Labels: Deployment

#125 100- menu-
  client/components/ActivityLog.jsx
  client/components/App.jsx
  client/components/BottomMenu.jsx
  client/components/CardList.jsx
  seeds/activities.js
  server/public/main.css
Labels: client

#127 Capitalised first letter (activities)
  seeds/activities.js
Labels: database, enhancement

#134 Pwa
  knexfile.js
  package.json
  seeds/a_users.js
  seeds/b_activities.js
  seeds/c_dates.js
  seeds/d_cardData.js
  yarn.lock
Labels: Deployment

#137 Added '-f' option to 'updateDB' script
  package.json
Labels: database

#145 created LoginForm
  client/components/LoginForm.jsx
  client/components/Main.jsx
Labels: client

#155 121 smile change onclick
  client/actions/records.js
  client/components/ActivityCard.jsx
  client/components/ActivityLog.jsx
  client/reducer/records.js
  package.json
  server/db/cardData.js
  server/routes/dates.js
  webpack-config/webpack.dev.js
  yarn.lock
Labels: client, database, redux

#157 153 display user data
  client/components/ActivityCard.jsx
  client/components/CardList.jsx
  client/components/MyCalendar.jsx
  server/public/main.css
Labels: client, redux

#160 159 editable logs
  client/components/ActivityCard.jsx
  client/components/ActivityLog.jsx
Labels: client

#170 changed medication to stress in seed data and added link and info.
  seeds/b_activities.js
Labels: database

#186 167 graph calendar component
  client/components/Graph.jsx
  client/components/Statistics.jsx
  server/public/main.css
Labels: client

#189 added 512 icon and adjusted web manifest
  server/public/images/touch/icon512.png
  server/public/manifest.webmanifest
Labels: Deployment

#200 added server tests
  knexfile.js
  tests/server/activities.test.js
  tests/server/db.test.js
  tests/server/routes.test.js
  tests/server/test-environment.js
Labels: server, test

#206 197 fix db pwa
  client/actions/graph.js
  client/actions/records.js
  client/components/BarChart.jsx
  client/components/MyCalendar.jsx
  client/components/Statistics.jsx
  knexfile.js
  seeds/b_activities.js
  server/db/cardData.js
  server/public/MyCalendar.css
  server/public/Photo.css
  server/routes/dates.js
  tests/server/activities.test.js
  tests/server/db.test.js
  tests/server/routes.test.js
  tests/server/test-environment.js
Labels: Deployment, bug

#207 created activityCard snapshot test
  client/components/ActivityCard.jsx
  tests/client/components/__snapshots__/activityCard.test.js.snap
  tests/client/components/__snapshots__/main.test.js.snap
  tests/client/components/activityCard.test.js
  tests/client/components/main.test.js
Labels: test

#222 197 fix db pwa
  client/actions/auth.js
  client/actions/graph.js
  client/actions/journalActions.js
  client/actions/records.js
  client/actions/user.js
  client/components/ActivityCard.jsx
  client/components/ActivityLog.jsx
  client/components/BarChart.jsx
  client/components/CardList.jsx
  client/components/LoginForm.jsx
  client/components/Main.jsx
  client/components/MyCalendar.jsx
  client/components/RegisterForm.jsx
  client/components/Statistics.jsx
  client/reducer/index.js
  package.json
  seeds/a_users.js
  seeds/b_activities.js
  server/auth/hashing.js
  server/auth/tokens.js
  server/db/users.js
  server/public/MyCalendar.css
  server/public/images/BeerPizza.png
  server/public/images/Crazy.png
  server/public/images/MoodLogo.png
  server/public/images/MoodLogoPhone.png
  server/public/images/sleep.png
  server/public/images/tech.png
  server/public/js/precache-manifest.7bb9c559c78b37d145a74b930405065d.js
  server/public/js/precache-manifest.f0901a317e2d1bd1d7dca0b58c3a8c69.js
  server/public/js/sw.js
  server/routes/auth.js
  server/routes/dates.js
  server/routes/users.js
  server/server.js
  tests/client/components/__snapshots__/activityCard.test.js.snap
  tests/client/components/__snapshots__/main.test.js.snap
  tests/client/components/activityCard.test.js
  tests/client/components/main.test.js
  yarn.lock
Labels: Deployment

#226 removed service worker remnants
  server/public/index.html
  server/public/js/precache-manifest.2a83d45f460e67cef8df784ac853941a.js
  server/public/js/precache-manifest.3a8a65670b0d90b42d58a30cac2f8237.js
  server/public/js/precache-manifest.40d3cd9dc28cc21646a085c296923b10.js
  server/public/js/precache-manifest.4fb98bff22ceb33c2446eeb38cd62b79.js
  server/public/js/precache-manifest.647c299f02f8c6b72a7b152392018243.js
  server/public/js/precache-manifest.6601cbb6526e07ea01b467b5403c2040.js
  server/public/js/precache-manifest.7bb9c559c78b37d145a74b930405065d.js
  server/public/js/precache-manifest.edc9c5899d2f80fe3e954a31ce18d247.js
  server/public/js/precache-manifest.f0901a317e2d1bd1d7dca0b58c3a8c69.js
  server/public/js/sw.js
  server/public/sw.js
  webpack-config/webpack.common.js
  yarn.lock
Labels: bug, database

#229 Margin fix
  client/components/MyCalendar.jsx
  server/public/MyCalendar.css
  server/public/main.css
Labels: enhancement

#227 New icons
  client/actions/graph.js
  client/actions/records.js
  client/components/ActivityCard.jsx
  client/index.js
  knexfile.js
  package.json
  server/db/cardData.js
  server/public/images/touch/icon128.png
  server/public/images/touch/icon144.png
  server/public/images/touch/icon168.png
  server/public/images/touch/icon192.png
  server/public/images/touch/icon48.png
  server/public/images/touch/icon512.png
  server/public/images/touch/icon72.png
  server/public/images/touch/icon96.png
  server/public/index.html
  server/public/manifest.webmanifest
  server/routes/dates.js
  webpack-config/webpack.common.js
  yarn.lock
Labels: Deployment
